### ISSUE TITLE
Bug: Layout in PrintTemplate is not working 

### ISSUE THREAD

**Issue by wondie** [Esri/feedback-js-api-next#144]
**Describe the bug**
Layout such as a4-portrait, a3-portrait are not working in PrintTemplate Layout. It only prints as A4 landscape.

**To Reproduce**
  ```
const template = new PrintTemplate({
      format: "pdf",
      layoutOptions: {
        authorText: this.authorText,
        copyrightText: this.copyrightText,
        legendLayers: [],
        titleText: this.printTitle,
        customTextElements
      },
      layout: 'a3-portrait',// Layout does not work. For some reason it only shows landscape
      exportOptions: {
        width: this.state.width,
        height: this.state.height,
        dpi: 300
      }
    });
```

**Expected behavior**
Portrait print if portrait is specified.  

**Browser** 
 - Chrome 96 on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: "Windows 10* 64-bit"
 - Device: "Windows Laptop PC" 

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.23.0-next.20220106, 4.22.2, 4.21.2

**Comment by NoashX** [comment]
Hi @wondie, thanks for posting this issue here. I tested the portrait layouts with next and they seem to print fine. I wonder if it's an issue with the print service you're using? Here is a test-app using the default utility print service:
https://codepen.io/noash/pen/KKXGbqG?editors=1000
(note: after clicking the print button, you will need to copy the link to the printout and open it in a new window as codepen blocks the initial printout page)

**Comment by wondie** [comment]
Thank you! That is true! It is the issue of the print service. I will sort it out.

**Comment by NoashX** [comment]
Awesome possum, thanks @wondie!
