### ISSUE TITLE
Bug: Measurement widget renders an empty div in expand widget

### ISSUE THREAD

**Issue by roemhildtg** [Esri/feedback-js-api-next#15]
**Describe the bug**
Instead of rendering the measurement widget, an empty div is rendered inside an expand widget.

**To Reproduce**
https://codepen.io/roemhildtg/pen/zYYWzeq?editors=1000

**Expected behavior**
Expand widget should render the measurement widget.

**Screenshots**
![image](https://user-images.githubusercontent.com/5471079/68245021-bc162780-ffdb-11e9-9414-d80e4a2f65d8.png)

**Browser (check https://whatismybrowser.com/)** 
Firefox 70
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10 

**API version (check your console)**
4.13-next

**Comment by RalucaNicola** [comment]
The div is empty because for the Measurement widget you need to build and configure the UI yourself.  See this sample on how to use it: https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=widgets-measurement
Let us know if you have more questions.

@NoashX in case you have nothing to add, I think we can close this issue?

**Comment by roemhildtg** [comment]
That makes sense. I didn't realize the widget didn't provide the buttons. Thanks @RalucaNicola!
