### ISSUE TITLE
Enhancement: Add support for drawing ellipses

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#167]
**Enhancement category**
[SketchViewModel](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch-SketchViewModel.html)

**Enhancement short summary**
Support for drawing ellipses when using the `SketchViewModel`.

**Enhancement description**
Support for drawing ellipses when using the `SketchViewModel`.

**Severity**
Medium

**Screenshots**

**API version (check your console)**
 - Version: [e.g. ArcGIS API for JavaScript 4.23-next [Date: 20220131, Revision: a737470f]]

**Additional context**
I know there is a Low-Level API provided by the [Draw](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-draw-Draw.html) module, but to be honest, this would require to implement our own SketchViewModel. This is definitely not what should be done in userland, but should actually be supported by the JS API core.

In addition the lack of this feature is a clear regression compared to 3.x

**Comment by banuelosj** [comment]
@sebastianfrey ,

Thanks for the feedback! This is a valid enhancement request, so the enhancement is being created. There are ways to create ellipse with sketchViewModel, but we don't expose a sketchViewModel.create("ellipse") option. This is what the enhancement is for.

It is currently possible to create a `circle` using `SketchViewModel.create()`. If you hold the `shift` key while drawing a circle, you will be able to create the `ellipse`. 

Also, you can listen for the circle tool, and call this undocumented property to also get this to work. Here is a test app:
```js
view.watch("activeTool", function(tool) {
  if (tool && tool.geometryType === "circle") {
    tool.forceUniformSize = false;
  }
});
```

https://codepen.io/banuelosj/pen/NWYmVzZ

These are workarounds for now, but the enhancement will be created. Then I will close this issue here in this repo.

**Comment by sebastianfrey** [comment]
@banuelosj This sounds great. Thanks for letting me know and thanks for providing a workaround CodePen!

**Comment by banuelosj** [comment]
Enhancement has been created internally, closing this issue out. If you would like to track this enhancement, a [Support Services](https://support.esri.com/en/contact-tech-support) ticket will need to be opened to create a new enhancement in support. Thanks again!
