### ISSUE TITLE
Bug: FeatureTable Date field time values showing in GMT

### ISSUE THREAD

**Issue by sirishbyreddy** [Esri/feedback-js-api-next#45]
**Describe the bug**
Time values in date field showing in GMT [GMT+08 is a time offset that adds 8 hours to Greenwich Mean Time (GMT)]

**To Reproduce**
1. Created new featureTable and passed the 'featureLayer'
    const featureTable = new FeatureTable({
   layer: featureLayer,                                            (Layer should have a DateTime Field)
   container: document.getElementById("tableDiv")
  });
2. Once FetureTable is loaded, timevalues are showing in GMT.

**Expected behavior**
FeatureTable should show date time values as per the source data.

**Screenshots**
Example: 
Source data : OBJECTID 1 --> date value is 12/22/2012 2:35:07 AM
Ouput in Feature Table : OBJECTID 1 --> date value is 12/22/2012 10:35

![ArcMapVSJsAPI](https://user-images.githubusercontent.com/18139951/80592056-5f0ea200-8a51-11ea-99ac-2f56dabb3884.jpg)

**Browser (check https://whatismybrowser.com/)** 
 - Chrome: Version 81.0.4044.122 (Official Build) (64-bit)
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: ArcGIS API for JavaScript next

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by pspraveenkr** [comment]
@sirishbyreddy - jsapi in general displays date-time values in the timezone of the device where your application is running. 

Can you provide more details about your workflow?
1. Is your feature layer published to ArcGIS Online or an Enterprise ArcGIS server?
2. What timezone did you set when publishing the service?
3. All feature layers have metadata related to time zone of the source data. For example: https://sampleserver6.arcgisonline.com/arcgis/rest/services/Earthquakes_Since1970/FeatureServer/0?f=pjson (look for properties like timeInfo, dateFieldsTimeReference, timeZone etc). Can you copy-paste that information to this issue?
4. Would it be possible to share the url for your feature layer so that we can better debug the issue?

**Comment by sirishbyreddy** [comment]
1) We are using Enterprise ArcGIS Server 10.6, is the dateFieldsTimeReference property applicable to ArcGIS Server 10.6 services?
2) Previously we didn't set timezone while publishing the service.
  now we applied timezone...below is the screenshot
![image](https://user-images.githubusercontent.com/18139951/80802940-6c5b9600-8be3-11ea-9a2e-5904f3a4d255.png)

With these changes, we are able to get the correct time values in FeatureTable.

Thanks @pspraveenkr for the suggestion

**Comment by pspraveenkr** [comment]
> 1. We are using Enterprise ArcGIS Server 10.6, is the dateFieldsTimeReference property applicable to ArcGIS Server 10.6 services?

Yes. It is.

> With these changes, we are able to get the correct time values in FeatureTable.

👍 We'll close this issue now. Pls feel free to re-open if you run into additional problems related to this issue.
