### ISSUE TITLE
Bug: Breaking the Editor Widget UI

### ISSUE THREAD

**Issue by tkamiya0625** [Esri/feedback-js-api-next#50]
**Describe the bug**
The UI of the Editor Widget is broken.

**To Reproduce**
1. https://codepen.io/tkamiya0625/pen/vYNzdqM
2. Click on the Edit widget.
3. Select a feature and edit it.
4. UI is broken

**Expected behavior**
In ver.4.14, it didn't break down.

**Screenshots**
![Editor widget updates Expand](https://user-images.githubusercontent.com/59276069/82004749-a0808d80-969e-11ea-9337-8af40048fe51.png)

**Browser (check https://whatismybrowser.com/)** 
 Windows 10 Edge, chrome, Firefox
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10 64-bit

**API version (check your console)**
- ArcGIS API for JavaScript 4.15
- ArcGIS API for JavaScript 4.15-next.20200416 [Revision: 43ef44a5]

**Additional context**
We have contacted support.

**Comment by bsvensson** [comment]
Hi @tkamiya0625 - thank you for reporting an issue with the ArcGIS API for JavaScript.

When you can reproduce the issue with a released version of the software, then contacting Esri Support is your best option.  Since you've already done that, there is no need to also report the same issue here.

Did you get a bug number or case number from Support?

**Comment by tkamiya0625** [comment]
Thank you very much.
No, it's a situation that hasn't been registered in the bug yet.

The case number will be #02545091.

**Comment by hgonzago** [comment]
This was logged using 4.15. I can't reproduce this. Can you try this using /next please? We are currently working on our next 4.18 release.
