### ISSUE TITLE
Enhancement: GraphicsLayer Zoom in/out performance

### ISSUE THREAD

**Issue by anonanonttl** [Esri/feedback-js-api-next#56]
Hi,

I've made a simple test with large data in a GraphicsLayer, I notice zoom in / out completely blocks the page, however map panning is not affected.

```
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1, maximum-scale=1, user-scalable=no"
    />
    <title>ArcGIS JavaScript Tutorials: Create a Starter App</title>
    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
      }
    </style>

    <link
      rel="stylesheet"
      href="https://js.arcgis.com/4.15/esri/themes/light/main.css"
    />
    <script src="https://js.arcgis.com/4.15/"></script>

    <script>
      require([
        "esri/Map",
        "esri/views/MapView",
        "esri/Graphic",
        "esri/layers/GraphicsLayer"
      ], function (Map, MapView, Graphic, GraphicsLayer) {
        var map = new Map({
          basemap: "gray-vector",
        });

        var view = new MapView({
          container: "viewDiv",
          map: map,
          zoom: 2,
        });

        var graphicsLayer = new GraphicsLayer();
        map.add(graphicsLayer);

        var simpleMarkerSymbol = {
          type: "simple-marker",
          color: [226, 119, 40],
          outline: {
            color: [255, 255, 255],
            width: 1,
          },
        };

        function getRandomInRange(from, to, fixed) {
          return (Math.random() * (to - from) + from).toFixed(fixed) * 1;
        }

        for (var i = 0; i < 500000; i++) {
          var point = {
            type: "point",
            longitude: getRandomInRange(-45, 45, 10),
            latitude: getRandomInRange(-45, 45, 10),
          };

          var pointGraphic = new Graphic({
            geometry: point,
            symbol: simpleMarkerSymbol,
          });

          graphicsLayer.add(pointGraphic);
        }
      });
    </script>
  </head>
  <body>
    <div id="viewDiv"></div>
  </body>
</html>
```

Thanks

**Comment by mpayson** [comment]
Have you tried adding this to a FeatureLayer instead of a GraphicsLayer? 
> https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer-collection/index.html

My understanding is they have a different engine, FeatureLayer is better suited for this use case (many features with consistent schema) where as GraphicsLayer is better for interactive edits on a couple ad-hoc features (the product team can also add their thoughts)

**Comment by anonanonttl** [comment]
Hi,

Thanks for your response,

Ya I tried to use my sample with feature layer, there is a big difference performance side.

Except we can't use feature layer, we have complexe graphic symbol, eg graphics with link labeling, cluster with flare and so on, so graphics layer is our better solution, besides that is what esri advised us.


the problem is the performance in terms of the number of graphic.

**Comment by mmgeorge** [comment]
@anonanonttl unfortunately like @mpayson mentioned the graphics layer is really geared towards low-latency editor type workflows. Because of the way the API for this works (with each graphic watching each possible property for updates), there's actually a limit to how fast we can make this without dramatically changing the public API. Once you get north of 10-20k graphics the performance is not going to be great. 

I'm not entirely familiar with your use case, but have you considered using a FeatureLayer with CIM symbology to handle the complex symbol requirements you have? 

See https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-CIMSymbol.html

**Comment by anonanonttl** [comment]
@mmgeorge 

CIM symbology  not work with sketch module if we want update geometry by party. Suppose we have a CIM Symbol composed by graphic original image icon, a labeling and a polyline like link between label and icon, we want just move the label and his link therefore moves. 

Actually we already use CIM symbology for our cluster layer.

**Comment by mmgeorge** [comment]
Ah ok basically you want to have a label callout and to be able to select the feature by selecting the label, and then drag it to another location?

**Comment by anonanonttl** [comment]
Yes, that’s it.

**Comment by mmgeorge** [comment]
It's definitely on our radar to look at adding support for label callouts/hittesting labels, but we don't yet have a timeline for that. So probably some kind of hybrid feature layer/graphics approach is best for now.
