### ISSUE TITLE
Bug: Labels for client-side feature layers do not display when printing a map

### ISSUE THREAD

**Issue by bbarnell** [Esri/feedback-js-api-next#70]
**Describe the bug**
#**BUG-000128004** Labels for client-side feature layers do not display when printing a map.
This issue has only been fixed for point features.  Labels for client side created polyline feature layers still don't print in the Next API 4.17

**To Reproduce**
Create a polyline feature layer in the Next API, label it and then try to print it with the PrintTask.

**Browser (check https://whatismybrowser.com/)** 
Chrome on Windows 10

**API version (check your console)**
 - Version: 4.17

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by NoashX** [comment]
Hi @bbarnell, thanks for reporting this issue. I tested this again and it still works for me using `next`. Could you provide a simplified reproducible test case? I would also recommend clearing your browser cache in case an older version of `next` is cached there.

test-app
https://codepen.io/noash/pen/MWydRpZ?editors=1000

test-app screenshot
![image](https://user-images.githubusercontent.com/2190813/94717386-18291f00-0305-11eb-8580-d24aabf5dc45.png)

printout screenshot
![image](https://user-images.githubusercontent.com/2190813/94717337-05aee580-0305-11eb-8fb6-275a68485f26.png)

**Comment by bbarnell** [comment]
I was able to reproduce the issue.  New in 4.17 you have to specify the LabelPlacement property for feature layer polylines.  There is only one valid value for this on polylines in feature layers, so I don't understand why it is now a requirement???

**From the documentation**:
FeatureLayer Polylines only support center-along label placement in 2D MapViews.

**Comment by NoashX** [comment]
@bbarnell - there are a couple of things going on here.

1) "New in 4.17 you have to specify the LabelPlacement property for feature layer polylines."
This is the same as it was at 4.16. I tested this to make sure. A valid labelPlacement property value is required. https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-LabelClass.html#labelPlacement

2) "There is only one valid value for this on polylines in feature layers, so I don't understand why it is now a requirement???"
This has been a requirement for a number of releases, but I think I understand your larger point. Currently, there is only one valid label placement (which might change at a future release) for FeatureLayer polylines. MapImageLayer polylines have more options. This issue is far more complex that I wish it was, but we are also trying to improve the labeling experience at every release, and I will make a note of your feedback.

**Comment by bbarnell** [comment]
Feature labels still won't print when there are lots of graphic text on the map.  Even when the labels are not even close to the graphic text, the built in conflict resolution still thinks they are too close to the graphic text to print.

**Comment by bbarnell** [comment]
This is working now.
